/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useEffect, useRef } from 'react'
import * as THREE from 'three'

export default function Model(props) {
  const group = useRef<THREE.Group>(null!)
  // @ts-ignore
  const { nodes, materials, animations } = useGLTF('/spaceship.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions['ConeAction'].play()
    actions['Cube.003'].play()
  }, [actions])

  // mesh emission material
  const material = new THREE.MeshStandardMaterial({
    color: new THREE.Color(1.5, 1.5, 0.3),
    emissive: new THREE.Color(1.8, 0, 0.3), // WHITE emissive COLOR
    emissiveIntensity: 2, // Intensity of emissive COLOR
  })
  material.toneMapped = false
  material.needsUpdate = true

  useFrame((state) => {
    if (!group.current) return
    const t = state.clock.getElapsedTime()
    group.current.rotation.set(
      Math.cos(t / 4) / 2,
      Math.sin(t / 4) / 2,
      Math.sin(t / 4) / 2
    )
  })

  return (
    <group ref={group} {...props} dispose={null} scale={2}>
      <group name="Scene">
        <group name="Cube003">
          <mesh
            name="Cube005"
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={materials.Mat0}
          />
          <mesh
            name="Cube005_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials.Mat1}
          />
          <mesh
            name="Cube005_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube005_2.geometry}
            material={materials.Mat2}
          />
          <mesh
            name="Cube005_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube005_3.geometry}
            material={materials.Window_Frame}
          />
          <mesh
            name="Cube005_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube005_4.geometry}
            material={materials.Mat4}
          />
          <mesh
            name="Cube005_5"
            castShadow
            receiveShadow
            geometry={nodes.Cube005_5.geometry}
            material={materials.Mat3}
          />
          <mesh
            name="Cube005_6"
            castShadow
            receiveShadow
            geometry={nodes.Cube005_6.geometry}
            material={materials.Window}
          />
        </group>
        <mesh
          name="Cone"
          castShadow
          receiveShadow
          geometry={nodes.Cone.geometry}
          material={material}
          position={[0.01, -0.46, -2.23]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/spaceship.gltf')
